---

- name: yum install required system packages.
  apt: pkg={{item}} state=installed
  tags: bootstrap
  with_items:
    - mesosphere-zookeeper

- name: Overwrite myid file.
  template: src=myid.j2 dest=/var/lib/zookeeper/myid
  tags: deploy

- name: Overwrite default config file
  template: src=zoo.cfg.j2 dest=/etc/zookeeper/conf/zoo.cfg
  notify: Restart zookeeper
  tags: deploy

- name: mkdir for zookeeper log
  file: path=/var/log/zookeeper state=directory mode=0755
  tags: deploy

- name: Start zookeeper
  service: name=zookeeper state=started enabled=yes
  tags: deploy
